########################################################## 80

<VirtualHost *:80>
ServerName example.com

ProxyPreserveHost On
ProxyPass / http://127.0.0.1:6091/
ProxyPassReverse / http://127.0.0.1:6091/

DocumentRoot /home/user/www/example.com

<IfModule security2_module>
    SecAuditEngine Off
    SecRuleEngine Off
</IfModule>

ErrorLog /home/user/logs/apache/example.com.error.log
CustomLog /home/user/logs/apache/example.com.access.log combined env=!dontlog

<Directory /home/user/www/example.com>
Options Indexes FollowSymLinks MultiViews Includes
AllowOverride All
Require all granted
</Directory>

########################################################## 433

</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>

ProxyPreserveHost On
ProxyPass / http://127.0.0.1:6091/
ProxyPassReverse / http://127.0.0.1:6091/
RequestHeader set X-Forwarded-Port "443"
RequestHeader set X-Forwarded-Proto "https"

SSLEngine on

SSLCertificateFile	/usr/local/acme.sh/example.com/fullchain.cer
SSLCertificateKeyFile /usr/local/acme.sh/example.com/example.com.key

ServerName example.com

DocumentRoot /home/user/www/example.com

<IfModule security2_module>
    SecAuditEngine Off
    SecRuleEngine Off
</IfModule>

ErrorLog /home/user/logs/apache/example.com.error.log
CustomLog /home/user/logs/apache/example.com.access.log combined env=!dontlog

<Directory /home/user/www/example.com>
Options Indexes FollowSymLinks MultiViews Includes
AllowOverride All
Require all granted
</Directory>

</VirtualHost>
</IfModule>

########################################################## FOR VARNISH

<VirtualHost *:2080>

ServerName example.com

DocumentRoot /home/user/www/example.com

<IfModule security2_module>
    SecAuditEngine Off
    SecRuleEngine Off
</IfModule>

ErrorLog /home/user/logs/apache/example.com.error.log
CustomLog /home/user/logs/apache/example.com.access.log combined env=!dontlog

<Directory /home/user/www/example.com>
Options Indexes FollowSymLinks MultiViews Includes
AllowOverride All
Require all granted
</Directory>

<FilesMatch \.php$>
    SetHandler "proxy:unix:/run/php/php7.4-example.com.sock|fcgi://localhost"
</FilesMatch>

</VirtualHost>
