domain.com
/home/aa93880-XXX/www/prod-m2/pub
/home/aa93880-XXX/www/prod-m2/
/etc/apache2/conf-available/extra-aa93880-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.conf
aa93880-XXX

<VirtualHost *:80>
ServerAdmin support@fast-mage.com
ServerName domain.com
ServerAlias www.domain.com

ProxyPreserveHost On
ProxyPass / http://127.0.0.1:10081/
ProxyPassReverse / http://127.0.0.1:10081/
</VirtualHost>

<VirtualHost *:8080>
ServerAdmin support@fast-mage.com
ServerName domain.com
ServerAlias www.domain.com

DocumentRoot /home/aa93880-XXX/www/prod-m2/pub

<IfModule security2_module>
    SecAuditEngine Off
    SecRuleEngine Off
</IfModule>

ErrorLog /home/aa93880-XXX/logs/apache/domain.com.error.log
CustomLog /home/aa93880-XXX/logs/apache/domain.com.access.log combined env=!dontlog

<Directory /home/aa93880-XXX/www/prod-m2/>

Options Indexes FollowSymLinks MultiViews Includes
AllowOverride All
Require all granted
</Directory>

# any extra conf text to include

IncludeOptional /etc/apache2/conf-available/extra-aa93880-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.conf

<FilesMatch \.php$>
    SetHandler "proxy:unix:/run/php/php7.4-aa93880-XXX.sock|fcgi://localhost"
</FilesMatch>

</VirtualHost>
<IfModule mod_ssl.c>



<VirtualHost *:443>

SSLEngine on
SSLCertificateFile	/usr/local/acme.sh/domain.com/fullchain.cer
SSLCertificateKeyFile /usr/local/acme.sh/domain.com/domain.com.key
ServerAdmin support@fast-mage.com

ServerName domain.com
ServerAlias www.domain.com


ProxyPreserveHost On
ProxyPass / http://127.0.0.1:10081/
ProxyPassReverse / http://127.0.0.1:10081/
RequestHeader set X-Forwarded-Port "443"
RequestHeader set X-Forwarded-Proto "https"
RequestHeader set SSL-OFFLOADED "https"

</VirtualHost>
</IfModule>
